### ISSUE TITLE
Support release builds and deployments in GitHub Actions

### ISSUE THREAD

**Issue by HeikoKlare** [vitruv-tools/Vitruv-Build-AggregatedUpdateSite#1]
The Maven build specification supports the creation of a release update site with automatic replacement of the aggreated update site from the nightly to release versions. The GitHub Actions workflow, however, does only handle the nightly builds yet. Thus, we need to adapt the Actions to also process a release build and deployment, and to properly trigger that release build.

**Comment by JanWittler** [comment]
To trigger the release I would suggest to use GitHub Releases as its done in all of our other repositories.
What do you mean with "automatic replacement of the aggregated update site"? I would have simply created a new update site with the release profile and deploy that one as a release.
